### ISSUE TITLE
How to obtain k_sigma, PS_sigma and  Omega_0_sigma ?

### ISSUE THREAD

**Issue by Saber-of-QFT** [SophieMLV/axionHMcode#1]
Hello, I met some problem when try to use this code to calculate halo mass function.

At the line 48 of halo_mass_function.py, 'def func_halo_mass_function(M, k_sigma, PS_sigma, cosmo_dic, Omega_0, Omega_0_sigma):' I found that func_halo_mass_function require k_sigma, PS_sigma and Omega_0_sigma. 

So I search for 'k_sigma' in your code, I find at the line 32 of PS_nonlin_axion.py: 'k_sigma = power_spec_dic_sigma['k']'. But I couldn't found a function call 'power_spec_dic_sigma' anywhere.

Is there any missing part in the code? Or did I misunderstanding the parameters of the func_halo_mass_function?

Can you help me? Thank you vary much!

**Comment by SophieMLV** [comment]
Hello,
'power_spec_dic_sigma' has to computed separately before you can start using  'PS_nonlin_axion.func_full_halo_model_ax' or also 'halo_mass_function. func_halo_mass_function'. How you can do this is shown in the example_file.py file. 
You can see there that in line 113 the function 'PS_nonlin_axion.func_full_halo_model_ax' takes for the argument 'power_spec_dic_sigma' the dictionary 'power_spec_interp_dic_ax' which is computed in line 91 by the function 'lin_power_spectrum.func_power_spec_interp_dic'.
You need another linear  power spectrum for the computation of the variance of the linear power spectrum because when you go to small halo masses you have to be sure that the integral for the variance converges. You don't need this power spectrum up to high k for the rest of the computation (to be precise you only need the linear power spectrum in the k range where you want you non-linear power spectrum). Therefore I first compute a linear power spectrum for the smaller k range and then extrapolate it with 'lin_power_spectrum.func_power_spec_interp_dic' for the computation of the variance.

I hope the answer helps you to run the code.

**Comment by Saber-of-QFT** [comment]
I see, so I use 'power_spec_interp_dic_ax['k']' as k_sigma, and 'power_spec_interp_dic_ax['power_total']' as PS_sigma, is that right?

But how do I compute 'Omega_0_sigma' ? I didn't find this term in the dictionary 'power_spec_interp_dic_ax'

**Comment by SophieMLV** [comment]
to your first point:
what you choose for PS_sigma depends if you have CDM only or a mix with ULAs. In the second case you use 'power_spec_interp_dic_ax['cold']' for PS_sigma because the peak hight variable is more universal when only the cold matter field is taken into account (see SEc. IIIB of my paper  https://arxiv.org/abs/2209.13445 and references there. ). For the first case it is 'power_spec_interp_dic_ax['power_total']' what is equal to 'power_spec_interp_dic_ax['cold']' for CDM only cosmology (if you have no neutrinos).

To your second point:
'Omega_0_sigma' comes form your parameters for the cosmology. You can see this again in the example_file.py file. There in line 56 the cosmology dictionary is created via the function 'load_cosmology.load_cosmology_input(input_file_path) ' form an input file which contains the cosmological parameters. And from this cosmology you take  'Omega_0_sigma'. Which should be 'Omega_db' in a mixed cosmology and 'Omega_m' for CDM only (again when you have no neutrinos).

I hope this explanation helps.

**Comment by Saber-of-QFT** [comment]
Thank you! The explanation is very clear and helpful. May I ask two more questions?

First, when calculating the halo mass function, we need critical overdensity delta_c. I found that in your code, delta_c is obtain by calling func_delta_c in overdensities.py. But this function is returning a constant. But I think in the axion cosmology, delta_c should be mass-dependent (see equation 9 of arxiv: 1608.02575 or chapter 3.1 of arxiv: 1307.1705) and this lead to a suppression on the low mass region of the halo mass function, for example, like the figure below (from Figure 5 of arxiv: 1608.02575) : 
![image](https://user-images.githubusercontent.com/44289053/196576779-ac2e24e4-f9e7-46a6-af3a-a5f5579ecbed.png)

And I use your code to plot a halo mass function with m_axion = 10^-24 eV, I got this :
![image](https://user-images.githubusercontent.com/44289053/196576929-2798355a-cc0a-4e87-bac2-e6696fe22733.png)
There is no suppression on the low mass region.

Another question is the amplitude of the halo mass function, it has several orders of magnitude lower than the amplitude that it should be. For example, I plot a halo mass function for CDM cosmology : 
![image](https://user-images.githubusercontent.com/44289053/196578501-4e875ce5-6758-41d0-b7fc-8c6d5f2f8d03.png)

It is much more lower than the black curve (which is stand for LCDM) of Figure 5 from arxiv: 1608.02575. And it is happend to be look like the curve of dn/dm (figure from https://halomod.readthedocs.io/en/latest/examples/getting_started.html) : 
![image](https://user-images.githubusercontent.com/44289053/196578755-b85c583b-5f0f-40eb-8942-e44b682651bd.png)

But I read your code, you calculate the derivate of sigma by calling func_dlnsigma2_dlnM, which is the derivate over dlnM, so the result of func_halo_mass_function should be dn/dlnM, not dn/dm. So it makes me really confused.

I'm sorry to bother you with so many questions. Can you help me? Thanks again.

**Comment by SophieMLV** [comment]
Hi:
To your first point: we use here a mixture of CDM and ULA (MDM). The figure your showed is for either pure CDM or pure ULA cosmology and does not apply here. Furthermore, we assume here (see the corresponding paper https://arxiv.org/abs/2209.13445  section IIIB ) that the ULAs are a biased tracer of the cold matter (CDM plus baryons, because we neglect effects form baryons on large scales, see paper again) and thus all relevant quantities are expressed in terms of the cold matter. So, we use the "normal" HMF.

To your second issue: as you saw there are some difference in the HMF and this is due to the fact that there are a lot of different definition of the HMF in the Literature. We use the definition $1/2 \rho/M^2 f(\nu)  dln \sigma^2 / dln M $ (see eq. 20 in our paper https://arxiv.org/abs/2209.13445) where some literature uses $1/2 \rho/M f(\nu)  dln \sigma^2 / dln M $. So I have an extra $1/M$ and form this the different scales come from. Both definition are correct. But you have to be careful which is used in any analysis.

I hope these explanations answered your questions.
